const data={
ru:{hero:"Твой автопарк.<br>Твои правила.<br><em>Одна платформа.</em>",desc:"Заказы, диспетчерская, водители, транспорт и отчёты. Всё необходимое для транспортной компании в одной системе.",benefit1:"30 полных дней бесплатно",benefit2:"Банковская карта не требуется",benefit3:"Нет автоматических списаний",back:"← К панели управления",notice:"DEMO: настоящая компания не регистрируется. Данные не отправляются на сервер.",formTitle:"Создать демо-компанию",formDesc:"Посмотри, как будет выглядеть подключение перевозчика.",free:"30 ДНЕЙ БЕСПЛАТНО",noCard:"Без банковской карты",companyLabel:"Название компании",fleetLabel:"Размер автопарка",fleet1:"1–5 автомобилей",fleet2:"6–20 автомобилей",fleet3:"21–60 автомобилей",fleet4:"Более 60 автомобилей",submit:"Открыть демо-панель →",disclaimer:"Это только демонстрация. Настоящий аккаунт не создаётся; пароль, электронная почта и платёжные данные не запрашиваются.",placeholder:"Например, City Transfer"},
he:{hero:"צי הרכב שלך.<br>הכללים שלך.<br><em>מערכת אחת.</em>",desc:"הזמנות, סדרנות, נהגים, רכבים ודוחות. כל הדרוש לניהול חברת הסעות במקום אחד.",benefit1:"30 ימים מלאים בחינם",benefit2:"אין צורך בכרטיס אשראי",benefit3:"ללא חיוב אוטומטי",back:"→ חזרה ללוח הבקרה",notice:"הדגמה: לא נוצרת חברה אמיתית. המידע אינו נשלח לשרת.",formTitle:"יצירת חברת הדגמה",formDesc:"כך נראה תהליך הצטרפות של חברת הסעות.",free:"30 ימים בחינם",noCard:"ללא כרטיס אשראי",companyLabel:"שם החברה",fleetLabel:"גודל הצי",fleet1:"1–5 רכבים",fleet2:"6–20 רכבים",fleet3:"21–60 רכבים",fleet4:"מעל 60 רכבים",submit:"פתיחת לוח הדגמה ←",disclaimer:"זוהי הדגמה בלבד. לא נוצר חשבון אמיתי. אין צורך בסיסמה, בדוא״ל או בפרטי תשלום.",placeholder:"לדוגמה, City Transfer"},
en:{hero:"Your fleet.<br>Your rules.<br><em>One platform.</em>",desc:"Bookings, dispatch, drivers, vehicles and reports. Everything a transport operator needs in one place.",benefit1:"30 full days free",benefit2:"No credit card required",benefit3:"No automatic charges",back:"← Back to dashboard",notice:"DEMO: no real company is registered. Nothing is sent to a server.",formTitle:"Create a demo company",formDesc:"Explore the onboarding experience for a transport company.",free:"30 DAYS FREE",noCard:"No credit card",companyLabel:"Company name",fleetLabel:"Fleet size",fleet1:"1–5 vehicles",fleet2:"6–20 vehicles",fleet3:"21–60 vehicles",fleet4:"More than 60 vehicles",submit:"Open demo dashboard →",disclaimer:"Demonstration only. No real account is created; no password, email or payment details are requested.",placeholder:"For example, City Transfer"}
};
function language(key){const obj=data[key]||data.ru;document.documentElement.lang=key;document.body.dir=key==="he"?"rtl":"ltr";for(const [field,value] of Object.entries(obj)){if(field==="placeholder")document.querySelector("#company").placeholder=value;else{const el=document.getElementById(field);if(el){if(field==="hero")el.innerHTML=value;else el.textContent=value;}}}document.querySelectorAll("[data-locale]").forEach(b=>b.classList.toggle("selected",b.dataset.locale===key));sessionStorage.setItem("transport_demo_locale",key);}
document.querySelectorAll("[data-locale]").forEach(b=>b.addEventListener("click",()=>language(b.dataset.locale)));
document.querySelector("#trialForm").addEventListener("submit",e=>{e.preventDefault();const name=document.querySelector("#company").value.trim();if(name.length<2)return;sessionStorage.setItem("transport_demo_company",name);sessionStorage.setItem("transport_demo_fleet",document.querySelector("#fleet").value);location.assign("./index.html");});
language(sessionStorage.getItem("transport_demo_locale")||"ru");
